/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    achievements: Achievement;
    events: Event;
    gallery: Gallery;
    projects: Project;
    resources: Resource;
    tutorials: Tutorial;
    simulators: Simulator;
    'build-targets': BuildTarget;
    members: Member;
    'member-roles': MemberRole;
    'member-categories': MemberCategory;
    'member-photo': MemberPhoto;
    forms: Form;
    'form-submissions': FormSubmission;
    'form-media': FormMedia;
    media: Media;
    tags: Tag;
    'tracked-events': TrackedEvent;
    users: User;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    events: {
      forms: 'forms';
    };
  };
  collectionsSelect: {
    achievements: AchievementsSelect<false> | AchievementsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    tutorials: TutorialsSelect<false> | TutorialsSelect<true>;
    simulators: SimulatorsSelect<false> | SimulatorsSelect<true>;
    'build-targets': BuildTargetsSelect<false> | BuildTargetsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'member-roles': MemberRolesSelect<false> | MemberRolesSelect<true>;
    'member-categories': MemberCategoriesSelect<false> | MemberCategoriesSelect<true>;
    'member-photo': MemberPhotoSelect<false> | MemberPhotoSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'form-media': FormMediaSelect<false> | FormMediaSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'tracked-events': TrackedEventsSelect<false> | TrackedEventsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'achievement-settings': AchievementSetting;
    'about-page': AboutPage;
    'home-featured-members': HomeFeaturedMember;
    'legal-pages': LegalPage;
    'support-pages': SupportPage;
  };
  globalsSelect: {
    'achievement-settings': AchievementSettingsSelect<false> | AchievementSettingsSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'home-featured-members': HomeFeaturedMembersSelect<false> | HomeFeaturedMembersSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'support-pages': SupportPagesSelect<false> | SupportPagesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: number;
  title: string;
  summary: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Date of the achievement (newest first)
   */
  date: string;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every image used across the site. Drag files in to upload in bulk.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * E.g., "Workshop", "Seminar", "Social Event"
   */
  category: string;
  title: string;
  /**
   * Auto-generates from the title. Enter your own if it clashes with another event.
   */
  slug: string;
  /**
   * When the event happens. Recent events get a NEW badge.
   */
  eventDate: string;
  /**
   * Online events show a meeting link instead of a venue.
   */
  eventMode: 'inPerson' | 'online';
  /**
   * Link attendees join the event through.
   */
  meetingLink?: string | null;
  /**
   * Forms attached to this event. Set the link from the form, not here.
   */
  forms?: {
    docs?: (number | Form)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Poster shown on the event card.
   */
  image?: (number | null) | Media;
  /**
   * Short tagline shown on the event card (max 200 characters).
   */
  shortDescription?: string | null;
  /**
   * Full details, shown when the event card is opened.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  venue?: {
    roomName?: string | null;
    floor?: string | null;
  };
  contact?: {
    /**
     * Email for questions about this event
     */
    email?: string | null;
    /**
     * Phone number for event inquiries
     */
    phone?: string | null;
  };
  location?: {
    /**
     * Full street address (e.g., "123 Main St, City, Country")
     */
    address?: string | null;
    /**
     * Click on the map to pin the exact event location
     */
    coords?: {
      lat?: number | null;
      lng?: number | null;
    };
    /**
     * Zoom level for the embedded map (1=world view, 18=street level)
     */
    zoom?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Forms shown on the website. Answers are stored under Form Submissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  /**
   * Auto-generates from the title. Enter your own if it clashes with another form.
   */
  slug: string;
  type: 'registration' | 'feedback' | 'general';
  /**
   * The event this form belongs to. The event page then links to it automatically.
   */
  relatedEvent?: (number | null) | Event;
  /**
   * Inactive forms show a closed message instead of the form
   */
  active?: boolean | null;
  /**
   * The questions below are shared by every section, but responses are kept separate.
   */
  sectionGroup?: boolean | null;
  /**
   * Leave empty for a normal, standalone form.
   */
  sectionOf?: (number | null) | Form;
  /**
   * What this section is called - e.g. A Section, or Day 1.
   */
  sectionLabel?: string | null;
  /**
   * Generated from the section label. Used in the URL.
   */
  sectionSlug?: string | null;
  /**
   * Set by the import script. Empty for forms authored here.
   */
  googleFormId?: string | null;
  /**
   * Lowest first. Sections without one fall back to their title.
   */
  sectionOrder?: number | null;
  /**
   * Optional - the form closes automatically after this time
   */
  deadline?: string | null;
  title: string;
  /**
   * Shown under the form title
   */
  description?: string | null;
  /**
   * Optional banner shown once, under the form title.
   */
  headerImage?: (number | null) | FormMedia;
  /**
   * Each step is one screen the person fills in before moving to the next. Group related questions together and add a step for each group.
   */
  steps?:
    | {
        stepTitle: string;
        /**
         * One line shown under the step title, telling the person what this screen is asking for.
         */
        stepDescription?: string | null;
        /**
         * Optional image shown at the top of this step, under its description.
         */
        stepImage?: (number | null) | FormMedia;
        /**
         * The questions on this step. A step with no questions is allowed if it has an image - use one to show a poster or a QR code.
         */
        fields?:
          | {
              label: string;
              fieldType:
                | 'text'
                | 'email'
                | 'phone'
                | 'number'
                | 'textarea'
                | 'select'
                | 'radio'
                | 'checkbox'
                | 'date'
                | 'imageUpload'
                | 'image';
              /**
               * Tells the club what this answer is, so it can be used automatically. Name and email are used for certificates. USN is format-checked.
               */
              role?: ('none' | 'name' | 'email' | 'usn') | null;
              required?: boolean | null;
              /**
               * Half-width fields pair up side by side on desktop
               */
              width?: ('full' | 'half') | null;
              placeholder?: string | null;
              /**
               * Optional hint shown under the field
               */
              helpText?: string | null;
              /**
               * Optional picture shown under this question’s label.
               */
              image?: (number | null) | FormMedia;
              /**
               * The picture to show. The label above is used as its caption.
               */
              displayImage?: (number | null) | FormMedia;
              /**
               * Choices offered for this question
               */
              options?:
                | {
                    option: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  confirmationMessage?: string | null;
  /**
   * Optional. Paste a Sheet URL to mirror responses there. Share it with the service account as an Editor first.
   */
  sheetId?: string | null;
  /**
   * Google Drive folder for attachments. Leave empty to use the default.
   */
  driveFolderId?: string | null;
  /**
   * Enable automated certificate generation for this form
   */
  showCertificate?: boolean | null;
  /**
   * Google Slides link for the certificate. The slide must contain {{name}}.
   */
  certificateTemplateDriveId?: string | null;
  /**
   * Immediate sends on submit. Scheduled sends at the time you set below.
   */
  certificateDelivery?: ('immediate' | 'scheduled') | null;
  /**
   * Default send time. Anyone not matched by a batch below goes out at this time.
   */
  certificateSendAt?: string | null;
  /**
   * Optional. Send different groups at different times, matched on one question.
   */
  certificateBatches?:
    | {
        label: string;
        /**
         * Exact wording of the question that identifies the group
         */
        matchField: string;
        /**
         * The answer that puts someone in this batch
         */
        matchValue: string;
        sendAt: string;
        id?: string | null;
      }[]
    | null;
  /**
   * How the name prints where {{name}} appears on the certificate itself
   */
  certificateNameCase?: ('asTyped' | 'upper' | 'title') | null;
  /**
   * How the name reads in the email body, independent of the certificate
   */
  certificateEmailNameCase?: ('asTyped' | 'upper' | 'title') | null;
  /**
   * Optional. {{event}} is replaced with this form’s title. Leave empty for the default subject.
   */
  certificateEmailSubject?: string | null;
  /**
   * Optional. {{name}} and {{event}} are filled in per person.
   */
  certificateEmailBody?: string | null;
  /**
   * Fills the other {{markers}} in the template. {{name}} and {{event}} are automatic.
   */
  certificatePlaceholders?:
    | {
        /**
         * Without the braces - for {{USN}} write USN.
         */
        key: string;
        source: 'question' | 'fixed' | 'perPerson';
        /**
         * Exact wording of the question whose answer goes here
         */
        questionLabel?: string | null;
        /**
         * Printed identically on every certificate for this form
         */
        fixedValue?: string | null;
        /**
         * Used when no per-person value is set. Leave empty to print nothing.
         */
        defaultValue?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images used inside forms, kept separate from the site media library.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-media".
 */
export interface FormMedia {
  id: number;
  /**
   * Describes the image for screen readers, e.g. "UPI payment QR code".
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    inline?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Drag photos in to upload them in bulk, then add a caption to each.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  _order?: string | null;
  /**
   * What is this photo? Shown on hover.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Member projects. The showcase arranges the cards itself.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Generated from the title.
   */
  slug: string;
  /**
   * One-line summary shown on the project card (max 200 characters)
   */
  description: string;
  /**
   * Optional. Without one the card is typeset instead.
   */
  thumbnail?: (number | null) | Media;
  /**
   * The result, shown large on the card. Leave empty if there is none.
   */
  award?: string | null;
  /**
   * Where it was won.
   */
  event?: string | null;
  /**
   * The year the project was built.
   */
  year?: number | null;
  /**
   * Who built this
   */
  team?: (number | Member)[] | null;
  /**
   * Categorize with tags (IoT, Robotics, PCB, etc.)
   */
  tags?: (number | Tag)[] | null;
  /**
   * Optional link to the source code (GitHub, GitLab, …)
   */
  repoUrl?: string | null;
  /**
   * Optional link to a live demo or video
   */
  demoUrl?: string | null;
  /**
   * The write-up: how it works, what it took, what broke. Optional.
   */
  content?:
    | (TextBlock | CodeBlock | TableBlock | GraphBlock | ImageBlock | VideoBlock | RowBlock | SimulatorLinkBlock)[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  fullName: string;
  /**
   * Optional. Without one, an avatar is generated instead.
   */
  photo?: (number | null) | MemberPhoto;
  /**
   * Only used to pick a generated avatar. Never shown on the site.
   */
  gender?: ('male' | 'female' | 'unspecified') | null;
  category: number | MemberCategory;
  /**
   * A member can hold multiple roles over time (e.g. Member, then President). First role listed is shown most prominently.
   */
  roles: (number | MemberRole)[];
  bio?: string | null;
  /**
   * e.g. 2021
   */
  startYear: number;
  /**
   * Leave empty if still active
   */
  endYear?: number | null;
  github?: string | null;
  linkedin?: string | null;
  socialAccounts?:
    | {
        platform?: ('twitter' | 'instagram' | 'facebook' | 'youtube' | 'tiktok' | 'other') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-photo".
 */
export interface MemberPhoto {
  id: number;
  /**
   * e.g., "Photo of John Doe"
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    profile?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-categories".
 */
export interface MemberCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Ascending shows the latest year first. Descending shows the oldest year.
   */
  batchOrder: 'oldestFirst' | 'newestFirst';
  /**
   * Position in the list. Lower numbers appear first.
   */
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-roles".
 */
export interface MemberRole {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Position in the list. Lower numbers appear first.
   */
  sortOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Resource tags for categorization and filtering
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * Auto-generates from the name. Enter your own if it clashes with another tag.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock".
 */
export interface TextBlock {
  /**
   * Formatted text content with support for bold, italic, lists, and more
   */
  text: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'textBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  /**
   * Programming language for syntax highlighting
   */
  language:
    | 'javascript'
    | 'typescript'
    | 'python'
    | 'java'
    | 'cpp'
    | 'csharp'
    | 'go'
    | 'rust'
    | 'ruby'
    | 'php'
    | 'swift'
    | 'kotlin'
    | 'html'
    | 'css'
    | 'sql'
    | 'bash'
    | 'yaml'
    | 'json'
    | 'markdown'
    | 'xml';
  /**
   * Paste or write your code here
   */
  code: string;
  /**
   * Optional caption or file name to display above the code
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'codeBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableBlock".
 */
export interface TableBlock {
  /**
   * Column headers for the table
   */
  headers: {
    header: string;
    id?: string | null;
  }[];
  /**
   * Table rows and cells
   */
  rows: {
    cells: {
      cell: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'tableBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GraphBlock".
 */
export interface GraphBlock {
  /**
   * Type of graph or diagram to display
   */
  graphType: 'mermaid' | 'drawio' | 'chartData' | 'html';
  /**
   * Draw one free at app.diagrams.net, then File → Publish → Link and paste it here.
   */
  drawioUrl?: string | null;
  /**
   * Mermaid diagram syntax (e.g., graph TD, flowchart, etc.)
   */
  mermaidDefinition?: string | null;
  /**
   * Chart data in JSON format (Chart.js compatible)
   */
  chartData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Custom HTML for embedding (use with caution)
   */
  html?: string | null;
  /**
   * Optional caption for the diagram
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'graphBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock".
 */
export interface ImageBlock {
  /**
   * Upload an image to display
   */
  image?: (number | null) | Media;
  /**
   * Optional caption or alt text for the image
   */
  caption?: string | null;
  /**
   * Display width of the image
   */
  size?: ('small' | 'medium' | 'large') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock".
 */
export interface VideoBlock {
  /**
   * Paste any YouTube link. The player appears on the page.
   */
  url: string;
  /**
   * Optional caption shown under the video
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'videoBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RowBlock".
 */
export interface RowBlock {
  /**
   * Number of columns in this row
   */
  columns: '1' | '2' | '3';
  /**
   * Blocks to display in this row (nested RowBlocks not supported)
   */
  blocks?: (TextBlock | CodeBlock | TableBlock | GraphBlock | ImageBlock | VideoBlock | SimulatorLinkBlock)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'rowBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SimulatorLinkBlock".
 */
export interface SimulatorLinkBlock {
  /**
   * Select the simulator to link to
   */
  simulator: number | Simulator;
  /**
   * Text to display on the action button
   */
  buttonText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'simulatorLinkBlock';
}
/**
 * External simulators students can launch. Drag rows to set the order they appear on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulators".
 */
export interface Simulator {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Generated from the title.
   */
  slug: string;
  /**
   * Shown on the card and at the top of the modal (max 200 characters)
   */
  description: string;
  thumbnail?: (number | null) | Media;
  tags?: (number | Tag)[] | null;
  difficulty?: ('beginner' | 'intermediate' | 'advanced') | null;
  /**
   * Estimated time to complete in minutes
   */
  estimatedTime?: number | null;
  /**
   * What the main button says. A browser tool opens a website; a desktop tool sends them to a download page.
   */
  launchType: 'website' | 'download';
  /**
   * Where the simulator actually lives, e.g. https://wokwi.com. Students open this from the modal.
   */
  launchUrl: string;
  /**
   * Optional walkthrough video. Plays inside the simulator popup.
   */
  videoUrl?: string | null;
  /**
   * Optional - setup steps, login notes, download instructions. Shown under the video in the modal.
   */
  content?:
    | (TextBlock | CodeBlock | TableBlock | GraphBlock | ImageBlock | VideoBlock | RowBlock | SimulatorLinkBlock)[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reference material and guides. Drag rows to set the order they appear on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Auto-generates from the title. Enter your own if it clashes with another page.
   */
  slug: string;
  /**
   * One-line summary shown in cards and previews (max 200 characters)
   */
  description: string;
  /**
   * Image displayed in cards
   */
  thumbnail?: (number | null) | Media;
  /**
   * Write the page in the Content tab, or paste a link and the site embeds it - a YouTube video, a PDF, a Google Drive file or folder, or a website.
   */
  source: 'manual' | 'link';
  /**
   * Paste the link exactly as your browser shows it. The preview below updates as you type.
   */
  externalUrl?: string | null;
  /**
   * Difficulty level for this resource
   */
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  /**
   * Categorize with tags (Python, React, Backend, etc.)
   */
  tags?: (number | Tag)[] | null;
  /**
   * Approximate time to complete this resource
   */
  estimatedReadTime?: number | null;
  /**
   * Optional badge on the card. "Coming Soon" also makes it unclickable.
   */
  badge?: ('featured' | 'popular' | 'essential' | 'comingSoon') | null;
  /**
   * The page body. Add text, code, images, diagrams and more as blocks.
   */
  content?:
    | (
        | TextBlock
        | CodeBlock
        | TableBlock
        | GraphBlock
        | ImageBlock
        | VideoBlock
        | RowBlock
        | AccordionBlock
        | SimulatorLinkBlock
        | BuildLinkBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock".
 */
export interface AccordionBlock {
  /**
   * Optional heading shown above the collapsible sections
   */
  heading?: string | null;
  /**
   * Each row becomes one collapsible section, in this order
   */
  items: {
    /**
     * The clickable title of this section
     */
    title: string;
    /**
     * Optional one-line description shown under the title, while collapsed
     */
    summary?: string | null;
    /**
     * Start this section expanded
     */
    defaultOpen?: boolean | null;
    blocks?: (TextBlock | CodeBlock | TableBlock | GraphBlock | ImageBlock | VideoBlock | SimulatorLinkBlock)[] | null;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'accordionBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BuildLinkBlock".
 */
export interface BuildLinkBlock {
  /**
   * The board whose Build page this card opens
   */
  buildTarget: number | BuildTarget;
  id?: string | null;
  blockName?: string | null;
  blockType: 'buildLinkBlock';
}
/**
 * Boards programmable from the Build page. Drag rows to set the order they appear on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "build-targets".
 */
export interface BuildTarget {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Generated from the title.
   */
  slug: string;
  /**
   * Shown on the card and at the top of the page (max 200 characters)
   */
  description: string;
  thumbnail?: (number | null) | Media;
  /**
   * Which in-browser editor the page embeds. New boards need a new option here.
   */
  editor: 'microbitPython';
  tags?: (number | Tag)[] | null;
  difficulty?: ('beginner' | 'intermediate' | 'advanced') | null;
  /**
   * Optional - shown above the editor. Firmware updates, cable tips, which browser to use.
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Step-by-step walkthroughs. Drag rows to set the order they appear on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorials".
 */
export interface Tutorial {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Auto-generates from the title. Enter your own if it clashes with another page.
   */
  slug: string;
  /**
   * One-line summary shown in cards and previews (max 200 characters)
   */
  description: string;
  /**
   * Image displayed in cards
   */
  thumbnail?: (number | null) | Media;
  /**
   * Write the page in the Content tab, or paste a link and the site embeds it - a YouTube video, a PDF, a Google Drive file or folder, or a website.
   */
  source: 'manual' | 'link';
  /**
   * Paste the link exactly as your browser shows it. The preview below updates as you type.
   */
  externalUrl?: string | null;
  /**
   * Difficulty level for this tutorial
   */
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  /**
   * Categorize with tags (Python, React, Backend, etc.)
   */
  tags?: (number | Tag)[] | null;
  /**
   * Approximate time to complete this tutorial
   */
  estimatedReadTime?: number | null;
  /**
   * Optional badge on the card. "Coming Soon" also makes it unclickable.
   */
  badge?: ('featured' | 'popular' | 'essential' | 'comingSoon') | null;
  /**
   * The page body. Add text, code, images, diagrams and more as blocks.
   */
  content?:
    | (
        | TextBlock
        | CodeBlock
        | TableBlock
        | GraphBlock
        | ImageBlock
        | VideoBlock
        | RowBlock
        | AccordionBlock
        | SimulatorLinkBlock
        | BuildLinkBlock
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Responses submitted through the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  /**
   * The form this response came from. It is cleared if that form is deleted so the response audit record remains.
   */
  form?: (number | null) | Form;
  /**
   * Taken from the question marked as the name. Printed on certificates.
   */
  submitterName?: string | null;
  /**
   * Taken from the question marked as the email. Certificates are sent here.
   */
  submitterEmail?: string | null;
  /**
   * Field id → answer. Stable across question renames.
   */
  answers:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The same answers against the question wording as it was at submit time.
   */
  answersByLabel?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Photos this person attached. Stored in the form’s Google Drive folder.
   */
  attachments?:
    | {
        label?: string | null;
        fieldId?: string | null;
        driveFileId?: string | null;
        fileName?: string | null;
        mimeType?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * When this person agreed to the privacy notice. Empty for imported rows.
   */
  consentAcceptedAt?: string | null;
  /**
   * Values printed on this person’s certificate. Unset ones use the form default.
   */
  certificateValues?:
    | {
        /**
         * Without the braces - for {{Place}} write Place.
         */
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Whether this person has been sent their certificate.
   */
  certificateStatus: 'notApplicable' | 'pending' | 'sent' | 'failed';
  certificateSentAt?: string | null;
  /**
   * Why the last send attempt failed, if it did.
   */
  certificateError?: string | null;
  /**
   * Set by the import script. Empty for responses submitted through the site.
   */
  googleResponseId?: string | null;
  /**
   * When this row was copied to the Google Sheet. Empty means not synced.
   */
  sheetSyncedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Anonymous counts for actions that do not load a page (simulator launches, code copies, contact taps). No visitor information is stored.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracked-events".
 */
export interface TrackedEvent {
  id: number;
  /**
   * Event name, from the allowlist in lib/trackEvent.
   */
  name: string;
  /**
   * What it happened to - a simulator slug, a code language.
   */
  detail?: string | null;
  /**
   * Page the action happened on.
   */
  path?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Admin logins. Add new ones with scripts/createBackupAdmin.ts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'achievements';
        value: number | Achievement;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'tutorials';
        value: number | Tutorial;
      } | null)
    | ({
        relationTo: 'simulators';
        value: number | Simulator;
      } | null)
    | ({
        relationTo: 'build-targets';
        value: number | BuildTarget;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'member-roles';
        value: number | MemberRole;
      } | null)
    | ({
        relationTo: 'member-categories';
        value: number | MemberCategory;
      } | null)
    | ({
        relationTo: 'member-photo';
        value: number | MemberPhoto;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'form-media';
        value: number | FormMedia;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'tracked-events';
        value: number | TrackedEvent;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  date?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  category?: T;
  title?: T;
  slug?: T;
  eventDate?: T;
  eventMode?: T;
  meetingLink?: T;
  forms?: T;
  image?: T;
  shortDescription?: T;
  description?: T;
  venue?:
    | T
    | {
        roomName?: T;
        floor?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
      };
  location?:
    | T
    | {
        address?: T;
        coords?:
          | T
          | {
              lat?: T;
              lng?: T;
            };
        zoom?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  _order?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  thumbnail?: T;
  award?: T;
  event?: T;
  year?: T;
  team?: T;
  tags?: T;
  repoUrl?: T;
  demoUrl?: T;
  content?:
    | T
    | {
        textBlock?: T | TextBlockSelect<T>;
        codeBlock?: T | CodeBlockSelect<T>;
        tableBlock?: T | TableBlockSelect<T>;
        graphBlock?: T | GraphBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        videoBlock?: T | VideoBlockSelect<T>;
        rowBlock?: T | RowBlockSelect<T>;
        simulatorLinkBlock?: T | SimulatorLinkBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextBlock_select".
 */
export interface TextBlockSelect<T extends boolean = true> {
  text?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock_select".
 */
export interface CodeBlockSelect<T extends boolean = true> {
  language?: T;
  code?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TableBlock_select".
 */
export interface TableBlockSelect<T extends boolean = true> {
  headers?:
    | T
    | {
        header?: T;
        id?: T;
      };
  rows?:
    | T
    | {
        cells?:
          | T
          | {
              cell?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GraphBlock_select".
 */
export interface GraphBlockSelect<T extends boolean = true> {
  graphType?: T;
  drawioUrl?: T;
  mermaidDefinition?: T;
  chartData?: T;
  html?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageBlock_select".
 */
export interface ImageBlockSelect<T extends boolean = true> {
  image?: T;
  caption?: T;
  size?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "VideoBlock_select".
 */
export interface VideoBlockSelect<T extends boolean = true> {
  url?: T;
  caption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RowBlock_select".
 */
export interface RowBlockSelect<T extends boolean = true> {
  columns?: T;
  blocks?:
    | T
    | {
        textBlock?: T | TextBlockSelect<T>;
        codeBlock?: T | CodeBlockSelect<T>;
        tableBlock?: T | TableBlockSelect<T>;
        graphBlock?: T | GraphBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        videoBlock?: T | VideoBlockSelect<T>;
        simulatorLinkBlock?: T | SimulatorLinkBlockSelect<T>;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SimulatorLinkBlock_select".
 */
export interface SimulatorLinkBlockSelect<T extends boolean = true> {
  simulator?: T;
  buttonText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  description?: T;
  thumbnail?: T;
  source?: T;
  externalUrl?: T;
  difficulty?: T;
  tags?: T;
  estimatedReadTime?: T;
  badge?: T;
  content?:
    | T
    | {
        textBlock?: T | TextBlockSelect<T>;
        codeBlock?: T | CodeBlockSelect<T>;
        tableBlock?: T | TableBlockSelect<T>;
        graphBlock?: T | GraphBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        videoBlock?: T | VideoBlockSelect<T>;
        rowBlock?: T | RowBlockSelect<T>;
        accordionBlock?: T | AccordionBlockSelect<T>;
        simulatorLinkBlock?: T | SimulatorLinkBlockSelect<T>;
        buildLinkBlock?: T | BuildLinkBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AccordionBlock_select".
 */
export interface AccordionBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        title?: T;
        summary?: T;
        defaultOpen?: T;
        blocks?:
          | T
          | {
              textBlock?: T | TextBlockSelect<T>;
              codeBlock?: T | CodeBlockSelect<T>;
              tableBlock?: T | TableBlockSelect<T>;
              graphBlock?: T | GraphBlockSelect<T>;
              imageBlock?: T | ImageBlockSelect<T>;
              videoBlock?: T | VideoBlockSelect<T>;
              simulatorLinkBlock?: T | SimulatorLinkBlockSelect<T>;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BuildLinkBlock_select".
 */
export interface BuildLinkBlockSelect<T extends boolean = true> {
  buildTarget?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tutorials_select".
 */
export interface TutorialsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  description?: T;
  thumbnail?: T;
  source?: T;
  externalUrl?: T;
  difficulty?: T;
  tags?: T;
  estimatedReadTime?: T;
  badge?: T;
  content?:
    | T
    | {
        textBlock?: T | TextBlockSelect<T>;
        codeBlock?: T | CodeBlockSelect<T>;
        tableBlock?: T | TableBlockSelect<T>;
        graphBlock?: T | GraphBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        videoBlock?: T | VideoBlockSelect<T>;
        rowBlock?: T | RowBlockSelect<T>;
        accordionBlock?: T | AccordionBlockSelect<T>;
        simulatorLinkBlock?: T | SimulatorLinkBlockSelect<T>;
        buildLinkBlock?: T | BuildLinkBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "simulators_select".
 */
export interface SimulatorsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  description?: T;
  thumbnail?: T;
  tags?: T;
  difficulty?: T;
  estimatedTime?: T;
  launchType?: T;
  launchUrl?: T;
  videoUrl?: T;
  content?:
    | T
    | {
        textBlock?: T | TextBlockSelect<T>;
        codeBlock?: T | CodeBlockSelect<T>;
        tableBlock?: T | TableBlockSelect<T>;
        graphBlock?: T | GraphBlockSelect<T>;
        imageBlock?: T | ImageBlockSelect<T>;
        videoBlock?: T | VideoBlockSelect<T>;
        rowBlock?: T | RowBlockSelect<T>;
        simulatorLinkBlock?: T | SimulatorLinkBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "build-targets_select".
 */
export interface BuildTargetsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  description?: T;
  thumbnail?: T;
  editor?: T;
  tags?: T;
  difficulty?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  fullName?: T;
  photo?: T;
  gender?: T;
  category?: T;
  roles?: T;
  bio?: T;
  startYear?: T;
  endYear?: T;
  github?: T;
  linkedin?: T;
  socialAccounts?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-roles_select".
 */
export interface MemberRolesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-categories_select".
 */
export interface MemberCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  batchOrder?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-photo_select".
 */
export interface MemberPhotoSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        profile?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  slug?: T;
  type?: T;
  relatedEvent?: T;
  active?: T;
  sectionGroup?: T;
  sectionOf?: T;
  sectionLabel?: T;
  sectionSlug?: T;
  googleFormId?: T;
  sectionOrder?: T;
  deadline?: T;
  title?: T;
  description?: T;
  headerImage?: T;
  steps?:
    | T
    | {
        stepTitle?: T;
        stepDescription?: T;
        stepImage?: T;
        fields?:
          | T
          | {
              label?: T;
              fieldType?: T;
              role?: T;
              required?: T;
              width?: T;
              placeholder?: T;
              helpText?: T;
              image?: T;
              displayImage?: T;
              options?:
                | T
                | {
                    option?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  confirmationMessage?: T;
  sheetId?: T;
  driveFolderId?: T;
  showCertificate?: T;
  certificateTemplateDriveId?: T;
  certificateDelivery?: T;
  certificateSendAt?: T;
  certificateBatches?:
    | T
    | {
        label?: T;
        matchField?: T;
        matchValue?: T;
        sendAt?: T;
        id?: T;
      };
  certificateNameCase?: T;
  certificateEmailNameCase?: T;
  certificateEmailSubject?: T;
  certificateEmailBody?: T;
  certificatePlaceholders?:
    | T
    | {
        key?: T;
        source?: T;
        questionLabel?: T;
        fixedValue?: T;
        defaultValue?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submitterName?: T;
  submitterEmail?: T;
  answers?: T;
  answersByLabel?: T;
  attachments?:
    | T
    | {
        label?: T;
        fieldId?: T;
        driveFileId?: T;
        fileName?: T;
        mimeType?: T;
        id?: T;
      };
  consentAcceptedAt?: T;
  certificateValues?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  certificateStatus?: T;
  certificateSentAt?: T;
  certificateError?: T;
  googleResponseId?: T;
  sheetSyncedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-media_select".
 */
export interface FormMediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        inline?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tracked-events_select".
 */
export interface TrackedEventsSelect<T extends boolean = true> {
  name?: T;
  detail?: T;
  path?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure timeline display and ordering preferences for achievements.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievement-settings".
 */
export interface AchievementSetting {
  id: number;
  /**
   * Choose whether the achievements timeline starts from the most recent achievements (newest first) or earliest achievements (oldest first).
   */
  sortOrder: 'desc' | 'asc';
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  title: string;
  /**
   * URL pointing to the original website (e.g. Netlify URL once embedclub.org domain transfers).
   */
  legacyWebsiteUrl?: string | null;
  /**
   * Intro text shown at the top of the page (rendered before the sections below).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Extra sections shown below the intro. Drag to reorder.
   */
  sections?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            /**
             * Optional image behind the heading
             */
            backgroundImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'bannerBlock';
          }
        | {
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutTextBlock';
          }
        | {
            image?: (number | null) | Media;
            caption?: string | null;
            position?: ('center' | 'left' | 'right') | null;
            size?: ('small' | 'medium' | 'large') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutImageBlock';
          }
      )[]
    | null;
  /**
   * Developers and contributors who worked or are working on the current (v2.0) website.
   */
  currentDevelopers?:
    | {
        name: string;
        role?: string | null;
        url?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Developers and contributors who built or added to the original (v1.0) embedclub.org website.
   */
  legacyDevelopers?:
    | {
        name: string;
        role?: string | null;
        url?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  heritageCommunityNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-featured-members".
 */
export interface HomeFeaturedMember {
  id: number;
  /**
   * Each row is a category plus the members to feature from it. Rows show top → bottom.
   */
  rows?:
    | {
        /**
         * The row label + which members you can pick below.
         */
        category: number | MemberCategory;
        /**
         * Members to show in this row (order = display order, up to 10).
         */
        members: (number | Member)[];
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Privacy policy, terms, and the consent line shown on forms.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  privacyTitle: string;
  /**
   * Intro text at the top of /privacy, shown before the sections below.
   */
  privacy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Sections shown below the intro on /privacy. Drag to reorder.
   */
  privacySections?:
    | (
        | {
            heading: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'legalHeadingBlock';
          }
        | {
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'legalTextBlock';
          }
      )[]
    | null;
  termsTitle: string;
  /**
   * Intro text at the top of /terms, shown before the sections below.
   */
  terms?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Sections shown below the intro on /terms. Drag to reorder.
   */
  termsSections?:
    | (
        | {
            heading: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'legalHeadingBlock';
          }
        | {
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'legalTextBlock';
          }
      )[]
    | null;
  /**
   * The sentence beside the consent tick-box on every form. Say what the details are used for - this is the notice, and the policy is the detail behind it. A link to the Privacy Policy is added to the end, so finish with something that leads into it ("… See the").
   */
  consentNotice?: string | null;
  /**
   * Shown at the top of both pages.
   */
  lastUpdated?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The /contact page. /support redirects here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-pages".
 */
export interface SupportPage {
  id: number;
  contactTitle: string;
  /**
   * Shown as a mailto card under the /contact intro.
   */
  contactEmail?: string | null;
  /**
   * Shown as a tel card under the /contact intro. Leave blank to omit.
   */
  contactPhone?: string | null;
  /**
   * Intro text at the top of /contact, shown above the email/phone cards.
   */
  contact?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Collapsible answers under the Support heading on /contact, below the email/phone cards. Drag to reorder.
   */
  supportFaq?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Sections shown below the intro on /contact. Drag to reorder.
   */
  contactSections?:
    | (
        | {
            heading: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'legalHeadingBlock';
          }
        | {
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'legalTextBlock';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievement-settings_select".
 */
export interface AchievementSettingsSelect<T extends boolean = true> {
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  title?: T;
  legacyWebsiteUrl?: T;
  content?: T;
  sections?:
    | T
    | {
        bannerBlock?:
          | T
          | {
              heading?: T;
              subheading?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        aboutTextBlock?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        aboutImageBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              position?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
      };
  currentDevelopers?:
    | T
    | {
        name?: T;
        role?: T;
        url?: T;
        description?: T;
        id?: T;
      };
  legacyDevelopers?:
    | T
    | {
        name?: T;
        role?: T;
        url?: T;
        description?: T;
        id?: T;
      };
  heritageCommunityNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-featured-members_select".
 */
export interface HomeFeaturedMembersSelect<T extends boolean = true> {
  rows?:
    | T
    | {
        category?: T;
        members?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  privacyTitle?: T;
  privacy?: T;
  privacySections?:
    | T
    | {
        legalHeadingBlock?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        legalTextBlock?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
      };
  termsTitle?: T;
  terms?: T;
  termsSections?:
    | T
    | {
        legalHeadingBlock?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        legalTextBlock?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
      };
  consentNotice?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-pages_select".
 */
export interface SupportPagesSelect<T extends boolean = true> {
  contactTitle?: T;
  contactEmail?: T;
  contactPhone?: T;
  contact?: T;
  supportFaq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  contactSections?:
    | T
    | {
        legalHeadingBlock?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        legalTextBlock?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'achievements'
      | 'events'
      | 'gallery'
      | 'projects'
      | 'resources'
      | 'tutorials'
      | 'simulators'
      | 'build-targets'
      | 'members'
      | 'member-roles'
      | 'member-categories'
      | 'member-photo'
      | 'forms'
      | 'form-submissions'
      | 'form-media'
      | 'media'
      | 'tags'
      | 'tracked-events'
      | 'users'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}